Restart ols if entrypoint is executed again

diff --git a/tag-latest/bin/demyx-entrypoint b/tag-latest/bin/demyx-entrypoint
--- a/tag-latest/bin/demyx-entrypoint
+++ b/tag-latest/bin/demyx-entrypoint
@@ -34,3 +34,13 @@ demyx_entrypoint() {
 #   Init.
 #
 demyx_entrypoint
+#
+#   Exec.
+#
+if [[ -n "$(pgrep lshttpd || true)" ]]; then
+    sudo -E demyx-lsws restart
+else
+    # Start OLS
+    sudo -E demyx-lsws
+    exec tail -f "${DEMYX_LOG}/ols.access.log" "${DEMYX_LOG}/ols.error.log"
+fi
